---
apiVersion: v1
kind: Service
metadata:
    name: ros-ssh
    annotations:
      metallb.universe.tf/allow-shared-ip: "ros"
spec:
    ports:
      - name: ssh
        port: 22
        targetPort: 22
      - name: vnc
        port: 5900
        targetPort: 5900
    selector:
      app: ros-ssh
        #type: ClusterIP
    type: LoadBalancer


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ros-ssh
  labels:
    app: ros-ssh
spec:
   
  selector:
    matchLabels:
      app: ros-ssh
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ros-ssh
    spec:
{{ if eq .Values.simulation.enabled false }}
      nodeSelector:
        robot: "vision" 
      tolerations:
        - key: "robot"
          operator: "Exists" 
{{ end }}

      volumes:
        - name: scripts
          configMap:
            name: ros-scripts
            defaultMode: 0777
        - name: launch
          configMap:
            name: launchfiles
            defaultMode: 0777
 
      serviceAccount: pod-service-access
      containers:
      - image: lala432/ros-dev:latest
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
        imagePullPolicy: Always
        name: ssh
        command: 
            - /scripts/ros-run.sh
        env:
          - name: ROS_WS
            value: /home/user/ros-workspace
          - name: ROS_MASTER_URI
            value: http://robot-ros-master:11311/ 
          - name: LAUNCH
            value: ssh

        volumeMounts:
          - name: scripts
            mountPath: /scripts
          - name: launch
            mountPath: /launch

