---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ros-6500
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ros-6500
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ros-6500
      annotations:
        lala: asdf
    spec:
      nodeSelector:
        robot: "vision"
      tolerations:
        - key: "robot"
          operator: "Exists"
      volumes:
        - name: usbbus
          hostPath:
            path: /dev/bus/usb
            type: Directory
        - name: input
          hostPath:
            path: /dev/input/
            type: Directory
        - name: scripts
          configMap:
            name: ros-scripts
            defaultMode: 0777

      containers:
        {{- if eq .Values.simulation.enabled false -}}
        - name: motor
          image: 'lala432/ros-dev:latest'
          command: 
            - /scripts/ros-run.sh
          env:
            - name: ROS_WS
              value: /home/user/ros-workspace
            - name: ROS_MASTER_URI
              value: http://robot-ros-master:11311/ 
            - name: LAUNCH
              value: motor
          volumeMounts:
            - name: scripts
              mountPath: /scripts
          resources: 
            limits:
              smarter-devices/ttyUSB0: 1
            requests:
              smarter-devices/ttyUSB0: 1
        {{- end }}
        - name: vision
          image: 'lala432/ros-dev:latest'
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            #fsGroup: 0
            privileged: true
 
          command: 
            - /scripts/ros-run.sh
          env:
            - name: ROS_WS
              value: /home/user/ros-workspace
            - name: ROS_MASTER_URI
              value: http://robot-ros-master:11311/ 
            - name: LAUNCH
              value: vision
          volumeMounts:
            - name: scripts
              mountPath: /scripts
            - mountPath: /dev/bus/usb
              name: usbbus
          resources:
            limits:
              gpu.intel.com/i915: 1
            requests:
              gpu.intel.com/i915: 1

      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext:
        fsGroup: 1000
      schedulerName: default-scheduler
  strategy:
    type: Recreate

