
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ros-loc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ros-loc
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ros-loc
      annotations:
        lala: asdf
    spec:
      #{{ if eq .Values.simulation.enabled false }}
      nodeSelector:
        robot: "vision" 
        #{{ end }}
      volumes:
        - name: scripts
          configMap:
            name: ros-scripts
            defaultMode: 0777
        - name: launch
          configMap:
            name: launchfiles
            defaultMode: 0777
      tolerations:
        - key: "robot"
          operator: "Exists"
      containers:
        - name: loc

          image: "{{ .Values.image.repository }}/{{ .Values.image.defaultname}}{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
 
          command: 
            - /scripts/ros-run.sh
          env:
            - name: ROS_WS
              value: /home/user/ros-workspace
            - name: ROS_MASTER_URI
              value: http://robot-ros-master:11311/ 
            - name: LAUNCH
              value: localization
            {{ if eq .Values.simulation.enabled true }}
            - name: LAUNCHENV
              value: simul
            {{ end }}
          volumeMounts:
            - name: scripts
              mountPath: /scripts
            - name: launch
              mountPath: /launch


  strategy:
    type: Recreate
