---
apiVersion: v1
kind: Service
metadata:
    name: roswebsocket
    annotations:
        metallb.universe.tf/allow-shared-ip: "ros"
spec:
    ports:
        - name: webviz-ws
          port: 9090
          targetPort: 9090
        - name: webviz
          port: 80
          targetPort: 8080
        - name: vnc
          port: 5900
          targetPort: 5900
    selector:
        app: ros-xserver
          #type: ClusterIP
    type: LoadBalancer
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ros-xserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ros-xserver
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ros-xserver
      annotations:
        lala: asdf
    spec:
{{ if eq .Values.simulation.enabled false }}
      nodeSelector:
        robot: "vision" 
      tolerations:
        - key: "robot"
          operator: "Exists" 
{{ end }}

      tolerations:
        - key: "robot"
          operator: "Exists"
      volumes:
        - name: scriptsvol
          configMap:
            name: ros-scripts
            defaultMode: 0777
        - name: launch
          configMap:
            name: launchfiles
            defaultMode: 0777



      containers:
        - name: webviz
          image: 'cruise/webviz'
        - name: websocket
          image: 'lala432/ros-dev:latest'
          command: 
            - /scripts/ros-run.sh
          env:
            - name: ROS_WS
              value: /home/user/ros-workspace
            - name: ROS_MASTER_URI
              value: http://robot-ros-master:11311/ 
            - name: LAUNCH
              value: wsbridge
          volumeMounts:
            - name: scriptsvol
              mountPath: /scripts
            - name: launch
              mountPath: /launch


        - name: robot-xserver
          image: 'lala432/ros-dev:latest'
          env:
            - name: ROS_WS
              value: /home/user/ros-workspace
            - name: BIND_PORT_RANGE
              value: 10000-12000
            - name: ROS_MASTER_URI
              value: http://robot-ros-master:11311/ 
            - name: LAUNCH
              value: dev
            - name: LAUNCH_IMU
              value: "false"
            - name: LAUNCH_MOTOR
              value: "false"
            - name: LAUNCH_HW
              value: "false"
            - name: LAUNCH_VISION
              value: "false"
            - name: LAUNCH_WSBRIDGE
              value: "false"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: scriptsvol
              mountPath: /scripts
            - name: launch
              mountPath: /launch
 
          imagePullPolicy: Always
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            #fsGroup: 0
            privileged: true
            capabilities:
              add:
                - SYS_PTRACE
                - NET_RAW
                - NET_ADMIN
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext:
        fsGroup: 1000
      schedulerName: default-scheduler
  strategy:
    type: Recreate

