# ouya
axis_linear: 4  # Forward/Back
scale_linear: 0.7
scale_linear_turbo: 1.5

axis_angular: 3  # Twist
scale_angular: 0.4

enable_button: 10  # Trigger
enable_turbo_button: 9  # Button 2 aka thumb button