#global_costmap:
#  update_frequency: 1.0
#  publish_frequency: 3.0
#  transform_tolerance: 50
#  resolution: 0.9
#  obstacle_range: 0.1
#  raytrace_range: 6.0
  #layer definitions
#  global_frame: map
#  robot_base_frame: base_link
#  track_unknown_space: true
  #origin_x: 596500
  #origin_y: 4956350
 # rolling_window: true
  #parameter_scoring: true
 # heading_scoring: true
  #rolling:
  #  map_topic: map
  #  subscribe_to_updates: true
  #plugins: 
  #  - {name: inflation,                 type: "costmap_2d::InflationLayer"}


global_costmap:
   global_frame: map
   robot_base_frame: base_link
   update_frequency: 20.0
   publish_frequency: 5.0
   transform_tolerance: 50.0000

#   width: 40.0
#   height: 40.0
#   resolution: 0.05
#   origin_x: -20.0
#   origin_y: -20.0
 #  static_map: true
 #  rolling_window: false

   plugins:
   - {name: static_layer, type: "costmap_2d::StaticLayer"}
#   - {name: obstacles_layer, type: "costmap_2d::ObstacleLayer"}
#   - {name: inflater_layer, type: "costmap_2d::InflationLayer"}

local_costmap:
   global_frame: odom
   robot_base_frame: base_link
   update_frequency: 20.0
   publish_frequency: 5.0
   transform_tolerance: 50.0000

   width: 10.0
   height: 10.0
   resolution: 0.05
   static_map: false
   rolling_window: true

lalala:
#  update_frequency: 1.0
#  publish_frequency: 3.0
#  transform_tolerance: 50
#  resolution: 0.9
  obstacle_range: 0.1
#  raytrace_range: 6.0
  #layer definitions
  robot_base_frame: base_link
#  track_unknown_space: true
#  rolling_window: true
  heading_scoring: true
  #parameter_scoring: true
#  static:
#    map_topic: map
#    subscribe_to_updates: true

  plugins: 
    - {name: inflation,                 type: "costmap_2d::InflationLayer"}
  #lalal: la
  #global_frame: odom_wheel
  rolling_window: true
  width: 10
  height: 10
