topics:

- name    : joypad
  topic   : bluetooth_vel
  timeout : 0.1
  priority: 100
- name    : joystick
  topic   : joystick_vel
  timeout : 0.1
  priority: 90
- name    : remote
  topic   : remote_vel
  timeout : 0.1
  priority: 80
- name    : web
  topic   : web_vel
  timeout : 0.1
  priority: 70
- name    : move_base
  topic   : move_base_vel
  timeout : 0.5
  priority: 10
#locks:
#- name    : e_stop
#  topic   : e_stop
#  timeout : 0.0
#  priority: 255