<?xml version="1.0"?>


<robot name="myfirst" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find robot_launch)/urdf/materials.urdf"/>

  <xacro:property name="base_width" value="0.38"/>
  <xacro:property name="base_length" value="0.910"/>
  <xacro:property name="base_height" value="0.01"/>
  <xacro:property name="base_xoff" value="0.20"/>
  <xacro:property name="base_zoff" value="0.02"/>


  <xacro:property name="bar_height" value="0.540"/>


  <xacro:property name="wheel_radius" value="0.085"/>
  <xacro:property name="wheel_width" value="0.05"/>
  <xacro:property name="wheel_ygap" value="0.045"/>
  <xacro:property name="wheel_zoff" value="0.0"/>
  <xacro:property name="wheel_xoff" value="0.0"/>

  <xacro:property name="caster_xoff" value="0.14"/>



  <!-- Robot Base -->
  <link name="base_link">
  <!-- middle in between wheels -->
    <visual>
      <geometry>
        <box size="0.1 ${base_width} 0.1"/>
      </geometry>
      <material name="Cyan" />
    </visual>
  </link>

  <link name="box_link">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="Black" />
    </visual>
  </link>

    <joint name="box_joint" type="fixed">
      <parent link="base_link"/>
      <child link="box_link"/>
      <origin xyz="${base_length / 2 - base_xoff} 0 0" rpy="0 0 0"/>
    </joint>

<!--
  <xacro:include filename="$(find robot_launch)/urdf/sensors/kinect2.urdf.xacro" />
  <xacro:kinect2 parent="base_link" name="KinectSensor2">
    <origin xyz="0 0 ${bar_height}" rpy="0 0 0" />
  </xacro:kinect2>
-->
  
  <xacro:include filename="$(find robot_launch)/urdf/imu.urdf.xacro" />
        <!-- The following kinect2_xacro defines the _kinect2_rgb_optical_frame
        And includes the fixed joint  -->
        <xacro:imu_sensor parent="base_link" xyz="0 0 0.30" rpy="0 0 0">
        </xacro:imu_sensor>
<!-- The following kinect2_xacro defines the _kinect2_rgb_optical_frame
        And includes the fixed joint  -->

	<!-- FIXME
  <xacro:include filename="$(find robot_launch)/urdf/kinect2.urdf.xacro" />
                <xacro:kinect2 parent="base_link" prefix="kinect">
      		<origin xyz="0 0 0.54" rpy="1.5708 3.14159 1.5708" />
        </xacro:kinect2>
		-->
  <!-- Robot Footprint -->
  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_footprint"/>
    <origin xyz="0.0 0.0 ${-(wheel_radius+wheel_zoff)}" rpy="0 0 0"/>
  </joint>

    <!-- Wheels -->
  <xacro:macro name="wheel" params="prefix x_reflect y_reflect">
    <link name="${prefix}_link">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="Gray">
          <color rgba="0.5 0.5 0.5 1.0"/>
        </material>
      </visual>
    </link>

    <joint name="${prefix}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_link"/>
      <origin xyz="${x_reflect*wheel_xoff} ${y_reflect*(base_width/2+wheel_ygap)} ${-wheel_zoff}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <!-- <xacro:wheel prefix="drivewhl_l" x_reflect="-1" y_reflect="1" />
  <xacro:wheel prefix="drivewhl_r" x_reflect="-1" y_reflect="-1" />
  -->
  <xacro:wheel prefix="left_wheel" x_reflect="-1" y_reflect="1" />
  <xacro:wheel prefix="right_wheel" x_reflect="-1" y_reflect="-1" />


    <!-- Caster Wheel -->
    <!--
  <link name="front_caster">
    <visual>
      <geometry>
        <sphere radius="${(wheel_radius+wheel_zoff-(base_height/2))}"/>
      </geometry>
      <material name="Cyan">
        <color rgba="0 1.0 1.0 1.0"/>
      </material>
    </visual>
  </link>

  <joint name="caster_joint" type="fixed">
    <parent link="base_link"/>
    <child link="front_caster"/>
    <origin xyz="${caster_xoff} 0.0 0.1" rpy="0 0 0"/>
  </joint>
-->

</robot>
