obstacle_range: 2.5
raytrace_range: 3.0
#footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
#robot_radius: ir_of_robot
inflation_radius: 0.55
plugins: []

#observation_sources: laser_scan_sensor


#laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: /scan_matched_points2, marking: true, clearing: true}

